// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

//[assembly: SuppressMessage("Naming", "CA1710:Identifiers should have correct suffix", Justification = "<Pending>", Scope = "type", Target = "~T:PW.Collections.CursoredList`1")]
//[assembly: SuppressMessage("Design", "CA1033:Interface methods should be callable by child types", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Collections.CursoredList`1.System#Collections#Generic#IEnumerable<T>#GetEnumerator~System.Collections.Generic.IEnumerator{`0}")]
//[assembly: SuppressMessage("Design", "CA1033:Interface methods should be callable by child types", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Collections.CursoredList`1.System#Collections#IEnumerable#GetEnumerator~System.Collections.IEnumerator")]
//[assembly: SuppressMessage("Usage", "CA2201:Do not raise reserved exception types", Justification = "<Pending>", Scope = "member", Target = "~M:PW.FailFast.Guard.NoNulls``1(System.Collections.Generic.ICollection{``0},System.String)")]
//[assembly: SuppressMessage("Design", "CA1000:Do not declare static members on generic types", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Functional.FunctionPipeline`1.Compose(System.Collections.Generic.IList{System.Func{`0,`0}})~System.Func{`0,`0}")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Would be breadking.", Scope = "type", Target = "~T:PW.Net.PeriodicPing.PingEventHandler")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "Would be breadking.", Scope = "type", Target = "~T:PW.Net.PeriodicPing.PingExceptionEventHandler")]
//[assembly: SuppressMessage("Performance", "CA1838:Avoid 'StringBuilder' parameters for P/Invokes", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Win32.SafeNativeMethods.StrFormatByteSizeW(System.UInt64,System.Text.StringBuilder,System.UInt32)~System.IntPtr")]
//[assembly: SuppressMessage("Design", "CA1069:Enums values should not be duplicated", Justification = "<Pending>", Scope = "type", Target = "~T:PW.Win32.FileAccess")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:PW.Functional.Options.ValueOrException`1")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:PW.Events.TypedSenderEventHandler`2")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:PW.Functional.Options.ValueOrNoneOrException`1")]
[assembly: SuppressMessage("Naming", "CA1711:Identifiers should not have incorrect suffix", Justification = "<Pending>", Scope = "type", Target = "~T:PW.Events.PayloadEventHandler`1")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "Not available in all supported .NET versions.", Scope = "member", Target = "~M:PW.IO.KnownFolders.SHGetKnownFolderPath(System.Guid,System.UInt32,System.IntPtr,System.IntPtr@)~System.Int32")]
[assembly: SuppressMessage("GeneratedRegex", "SYSLIB1045:Convert to 'GeneratedRegexAttribute'.", Justification = "Not available in all supported .NET versions.", Scope = "member", Target = "~P:PW.Extensions.StringExtensions.UpperCamelCaseRegex")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Win32.SafeNativeMethods.AddFontMemResourceEx(System.IntPtr,System.UInt32,System.IntPtr,System.UInt32@)~System.IntPtr")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Win32.SafeNativeMethods.CreateFile(System.String,PW.Win32.FileAccess,PW.Win32.FileShare,System.IntPtr,PW.Win32.FileMode,PW.Win32.FileAttributes,System.IntPtr)~Microsoft.Win32.SafeHandles.SafeFileHandle")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Win32.SafeNativeMethods.Wow64DisableWow64FsRedirection(System.IntPtr@)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Win32.SafeNativeMethods.Wow64RevertWow64FsRedirection(System.IntPtr)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Win32.SafeNativeMethods.MoveFile(System.String,System.String)~System.Boolean")]
[assembly: SuppressMessage("Interoperability", "SYSLIB1054:Use 'LibraryImportAttribute' instead of 'DllImportAttribute' to generate P/Invoke marshalling code at compile time", Justification = "<Pending>", Scope = "member", Target = "~M:PW.Win32.SafeNativeMethods.StrCmpLogicalW(System.String,System.String)~System.Int32")]
